name: GitHub Actions Build and Deploy linux-command
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run build
    - run: npm run dash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.deploy
        